sudo:            false
language:        python
services:
  - postgresql

addons:
  postgresql:    "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_install:
  - sudo service postgresql stop
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/10/main
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql start 10
  # wait for the postgres docker to be running
  - while ! pg_isready -h localhost -p 5432 -q -U postgres; do "Postgres is unavailable - sleeping"; sleep 1; done;
  - psql -c "CREATE USER simpleml with password 'simpleml' SUPERUSER;" -U postgres

install:
  - pip install pip --upgrade
  - pip install psycopg2
  - pip install coveralls

script:
  - pip install -e .[all]
  - coverage run

after_success:
  - coverage combine
  - coverage report -m

matrix:
  include:
    - python:    3.6
    - python:    3.7
      dist:      xenial
      sudo:      true
    - python:    3.8
      dist:      xenial
      sudo:      true

deploy:
  provider:      pypi
  user:          $PYPI_USERNAME
  password:      $PYPI_PASSWORD
  on:
    tags:        true
    branch:      master
  skip_existing: true
