sudo: false
language: python
services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_install:
  - sudo service postgresql stop
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/10/main
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql start 10
  # wait for the postgres docker to be running
  - while ! pg_isready -h localhost -p 5432 -q -U postgres; do "Postgres is unavailable - sleeping"; sleep 1; done;
  - psql -c "CREATE USER simpleml with password 'simpleml' SUPERUSER;" -U postgres

install:
 - pip install psycopg2
 - pip install coveralls
 - pip install flake8

python:
  - 2.7
  - 3.5
  - 3.6

script:
  - flake8 . --ignore=E121,E221,E251,E261,E266,E302,E303,E305,F401,E402,E501,E502 --exclude=.git,.tox,build,dist
  - coverage run setup.py test

after_success:
  - coverage combine
  - coveralls

matrix:
  include:
    - python: 3.2
      dist: trusty
      script: python setup.py test
      after_success: True
    - python: 3.3
      dist: trusty
      script: python setup.py test
      after_success: True
    - python: 3.4
      script: python setup.py test
      after_success: True
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
    - python: pypy
      script: python setup.py test
      after_success: True
    - python: pypy3
      script: python setup.py test
      after_success: True
  allow_failures:
    - python: 2.7
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: pypy
    - python: pypy3


deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    branch: master
  skip_existing: true

# Flake8 Ignored Syntax
# Codes: http://flake8.pycqa.org/en/latest/user/error-codes.html
# E121, # continuation line under-indented for hanging indent
# E221, # multiple spaces before operator
# E251, # unexpected spaces around keyword / parameter equals
# E261, # at least two spaces before inline comment
# E266, # too many leading '#' for block comment
# E302, # too many blank lines
# E303, # too many blank lines
# E305, # expected 2 blank lines after class or function definition
# F401, # '' imported but unused
# E402, # module level import not at top of file
# E501, # line too long
# E502, # the backslash is redundant between brackets
