"""Empty Database

Revision ID: 0680f18b52ca
Revises:
Create Date: 2019-01-22 20:10:03.581025

"""

# revision identifiers, used by Alembic.
revision = '0680f18b52ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
