name:                   Lint

on:                     [push, pull_request]

jobs:
  flake8:
    runs-on:            ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses:             actions/checkout@v2
    - name:             Set up Python ${{ matrix.python-version }}
      uses:             actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name:             Install Dependencies
      run:              |
        python -m pip install --upgrade pip
        pip install 'flake8==5.0.4' 'black==23.1.0' 'isort==5.11.5'
    - name:             flake8
      run:              |
        flake8 . --ignore=E121,E203,E221,E251,E261,E266,E302,E303,E305,F401,E402,E501,E502,W503 --exclude=.git,.tox,build,dist
        python -m isort * --check-only --profile black
        python -m black --check .

# Flake8 Ignored Syntax
# Codes:                http://flake8.pycqa.org/en/latest/user/error-codes.html
# E121, # continuation line under-indented for hanging indent
# E221, # multiple spaces before operator
# E251, # unexpected spaces around keyword / parameter equals
# E261, # at least two spaces before inline comment
# E266, # too many leading '#' for block comment
# E302, # too many blank lines
# E303, # too many blank lines
# E305, # expected 2 blank lines after class or function definition
# F401, # '' imported but unused
# E402, # module level import not at top of file
# E501, # line too long
# E502, # the backslash is redundant between brackets
# W503, # line break before binary operator (considered an anti-pattern in W504)
