name:                   Type-Check

on:                     [push, pull_request]

jobs:
  mypy:
    runs-on:            ubuntu-latest
    name:               Mypy
    steps:
    - uses:             actions/checkout@v1
    - name:             Set up Python 3.7
      uses:             actions/setup-python@v1
      with:
        python-version: 3.7
    - name:             Install Dependencies
      run:              |
        pip install mypy
    - name:             mypy
      run:              |
        mypy --install-types --non-interactive simpleml/
